apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-pv-data
  namespace: cicd
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/synoti21/sonarqube/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-pv-extensions
  namespace: cicd
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/synoti21/sonarqube/extensions"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-extensions
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarqube
  name: sonarqube
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:latest
          volumeMounts:
            - mountPath: "/opt/sonarqube/data/"
              name: sonarqube-pv-data
            - mountPath: "/opt/sonarqube/extensions/"
              name: sonarqube-pv-extensions
          env:
            - name: "SONARQUBE_JDBC_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: "SONARUQBE_JDBC_URL"
              value: jdbc:postgresql://postgres.cicd.svc.cluster.local:5432/postgresdb
            - name: "SONARQUBE_JDBC_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
          ports:
            - containerPort: 9000
              protocol: TCP
      volumes:
        - name: sonarqube-pv-data
          persistentVolumeClaim:
            claimName: sonar-data
        - name: sonarqube-pv-extensions
          persistentVolumeClaim:
            claimName: sonar-extensions
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarqube
  name: sonarqube
  namespace: cicd
spec:
  ports:
    - name: sonar
      port: 80
      protocol: TCP
      targetPort: 9000
      nodePort: 32300
  selector:
    app: sonarqube
  type: NodePort

