apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-quickstart
  namespace: default
spec:
  version: 8.14.3
  count: 1
  elasticsearchRef:
    name: quickstart
  kibanaRef: 
    name: quickstart
