kind: Service
apiVersion: v1
metadata:
  name: mongo-nodeport
  namespace: mongodb
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports: # 서비스에 맞게 변경
    - name: mongo-nodeport
      port: 27017
      targetPort: 27017
      protocol: TCP
      nodePort: 31088
  selector:
    app: mongo
