---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cert-manager-certificate
spec:
  secretName: mongodb-tls
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: "*.mongodb-pod-svc.mongodb.svc.cluster.local"
  dnsNames:
  - "*.mongodb-pod-svc.mongodb.svc.cluster.local"
  - 192.168.0.10:31181
